```yaml
name: Build SRC Extensions

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      # Install Rush CLI
      - name: Install Rush CLI
        run: |
          curl https://raw.githubusercontent.com/shreyashsaitwal/rush-cli/main/scripts/install/install.sh -fsSL | sh

      # Build Extension
      - name: Build Extension
        run: |
          cd SRCStringHelper
          rush build --release -r

      # Debug Generated Files
      - name: Show Generated Files
        run: |
          find SRCStringHelper

      # Upload AIX
      - name: Upload .aix
        uses: actions/upload-artifact@v4
        with:
          name: SRCStringHelper
          path: |
            SRCStringHelper/out/**/*.aix
            SRCStringHelper/build/**/*.aix
            SRCStringHelper/dist/**/*.aix

```
